title: Yuewen Dai # your name (or website title) here
logo: "/images/logo.png?raw=true" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  <b>Analyze and Design for our cities </b>
  <br></br>
  <br>Master of Urban Spatial Analytics @ UPenn<br>
  <br>B.Arch @ Huahzong University of Science and Technology<br> 
  <i><br>I'm exploring the field of data analysis, design and visualization. </br></i>
  <a href="https://www.linkedin.com/in/yuewen-dai-a34159257/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
